### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by juliettef** [juliettef/imgui_markdown#10]
imgui_markdown currently requires C++14 due to the use of aggregate initializers along with default member initializers. Adding C++11 constructors would break users' code in a way that would be difficult to workaround, and adding initializer list constructors is somewhat of a pain.

Question: do you need C++11 support and why?

**Comment by NewYaroslav** [comment]
Добрый день! Нужна поддержка. Был бы очень благодарен!

**Comment by dougbinks** [comment]
We've updated the code with backwards compatible C++11 support, along with modifying the example to show how to use this.

The ability to use aggregate initialization in C++14 with default member initializers makes imgui_markdown is easier to use in C++14. Sadly adding C++11 style constructors would break this, so this approach seems to be the best of both worlds.
