### ISSUE TITLE
Any hope of adding bold and italic?

### ISSUE THREAD

**Issue by frink** [juliettef/imgui_markdown#11]
Markdown always has bold and italic formatting - which are very useful for emphasis. While I know official Dear Imgui has stated no interest in text formatting I thought maybe you would find interest in adding them.

**Comment by juliettef** [comment]
Yes, we could do it the same way we handle headings i.e. by enabling specifying fonts for bold and italics. We're snowed under with work at the moment so it could be a while before we implement it.

**Comment by frink** [comment]
That would be amazing. That pretty much the whole Markdown in a Dear Imgui widget...

**Comment by mekhontsev** [comment]
I've just created PR for it.

**Comment by juliettef** [comment]
PR #18 now merged with modifications
