### ISSUE TITLE
ImageCallback How to use?

### ISSUE THREAD

**Issue by jiangyi0923** [juliettef/imgui_markdown#20]
i need dx9 and dx11 methods 

thank you

**Comment by dougbinks** [comment]
There is an example `ImageCallback` function in the Readme.md at https://github.com/juliettef/imgui_markdown

Loading DX9 and DX11 images is beyond the scope of this project, but there is [more information and examples of how to load an `ImTextureID` on the Dear ImGui website](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples).
