### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by ZoozleDev** [juliettef/imgui_markdown#22]
[Here](https://raw.githubusercontent.com/juliettef/Media/main/imgui_markdown_icon_font.jpg) You show "This is an icon"

I would like to see the code for that since I would like to use ICON_FA_STAR in the markdown but cannot get it to work

Thank you in advance

**Comment by dougbinks** [comment]
See the following project:
https://github.com/juliettef/IconFontCppHeaders#example-code

[EDIT] However to get the icon in Markdown you need to copy the actual unicode icon from a cheatsheet into your UTF8 code, for example:

```
const char markdownText = u8R"(   an icon )";
```

**Comment by ZoozleDev** [comment]
Oh ok that did it. Thank you so much
