### ISSUE TITLE
imgui_markdown does not display the last character

### ISSUE THREAD

**Issue by BrutPitt** [juliettef/imgui_markdown#3]
Hi

As mentioned on twitter I started using **imgui_markdown** in **glChAoS.P**

Using **imgui_markdown** with my help strings I realized that it does not display the last character.

If the string is in form:
``` cpp
std::string markdownText = u8R"(
aaaaaP
)";
```
the problem does not seem to appear, because the last char is `\n`, but if I use:
`std::string markdownText = u8R"(aaaaaP)";`
or a more simple:
`std::string markdownText = "aaaaP";`
the `P` is not printed.

Thanks

**Comment by juliettef** [comment]
Thanks, I'll take a look.

**Comment by dougbinks** [comment]
Fixed - we weren't handling non-null terminated strings, as although we'd put std::string in our example we don't use them internally.

**Comment by BrutPitt** [comment]
Thanks!
