### ISSUE TITLE
No or wrong text wrapping for links and headings.

### ISSUE THREAD

**Issue by rcane** [juliettef/imgui_markdown#6]
There are two problems with the current code concerning text wrapping:

* Headings are wrapped at the wrong position because ```TextRegion``` always uses the normal text font to compute the wrap position but the font of a heading is usually larger than that.
* Links are not wrapped at all. Shouldn't the code use the ```RenderLine()``` function like the other text elements do?

**Comment by juliettef** [comment]
Thanks for your feedback, I've fixed the header wrapping. 
Links not wrapping is more difficult to implement, a fix may be done later.

**Comment by juliettef** [comment]
Thanks again, we were able to get the link wrap to work.
