### ISSUE TITLE
math formula support

### ISSUE THREAD

**Issue by huangatlas** [juliettef/imgui_markdown#8]
Thanks a lot ! imgui_markdown is exactly the library I am looking for. 
I have one question that whether it can support math formula input as the markdown extension does? Or any solution/advice for doing this?

**Comment by dougbinks** [comment]
No, this doesn't support math formula, it only supports [very basic markdown as listed in the readme](https://github.com/juliettef/imgui_markdown/blob/master/README.md).

Adding math formula support would be very difficult, it would require not only a way to parse the math input but also a way to render the output using Dear ImGui. Whilst using a font with math symbols would allow for some simple expressions to look reasonable, supporting the full range of positioning would be hard.

If someone was interested in undertaking this, a possibility might be to fork a library like [cLaTexMath](https://github.com/NanoMichael/cLaTeXMath) to use Dear ImGui.
